// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantMenuInfrastructure;

#nullable disable

namespace RestaurantMenuInfrastructure.Migrations
{
    [DbContext(typeof(BdrestaurantMenuContext))]
    partial class BdrestaurantMenuContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantMenuDomain.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("CATEGORIES", (string)null);
                });

            modelBuilder.Entity("RestaurantMenuDomain.Model.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("description");

                    b.Property<DateTime>("Period")
                        .HasColumnType("datetime")
                        .HasColumnName("period");

                    b.HasKey("Id");

                    b.ToTable("DISCOUNTS", (string)null);
                });

            modelBuilder.Entity("RestaurantMenuDomain.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Categoriesid")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("description");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.HasIndex("Categoriesid");

                    b.ToTable("PRODUCTS", (string)null);
                });

            modelBuilder.Entity("RestaurantMenuDomain.Model.ProductDiscount", b =>
                {
                    b.Property<int>("Discountsid")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Productsid")
                        .HasColumnType("int");

                    b.HasIndex("Discountsid");

                    b.HasIndex("Productsid");

                    b.ToTable("PRODUCT DISCOUNTS", (string)null);
                });

            modelBuilder.Entity("RestaurantMenuDomain.Model.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("comment");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime")
                        .HasColumnName("data");

                    b.Property<decimal>("Mark")
                        .HasColumnType("numeric(2, 1)")
                        .HasColumnName("mark");

                    b.Property<int>("Productsid")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Productsid");

                    b.ToTable("REVIEWS", (string)null);
                });

            modelBuilder.Entity("RestaurantMenuDomain.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Number")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("number");

                    b.HasKey("Id");

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("RestaurantMenuDomain.Model.UserProduct", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Productsid")
                        .HasColumnType("int");

                    b.Property<int>("Usersid")
                        .HasColumnType("int");

                    b.HasIndex("Productsid");

                    b.HasIndex("Usersid");

                    b.ToTable("USER PRODUCTS", (string)null);
                });

            modelBuilder.Entity("RestaurantMenuDomain.Model.Product", b =>
                {
                    b.HasOne("RestaurantMenuDomain.Model.Category", "Categories")
                        .WithMany("Products")
                        .HasForeignKey("Categoriesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_PRODUCTS_CATEGORIES");

                    b.Navigation("Categories");
                });

            modelBuilder.Entity("RestaurantMenuDomain.Model.ProductDiscount", b =>
                {
                    b.HasOne("RestaurantMenuDomain.Model.Discount", "Discounts")
                        .WithMany()
                        .HasForeignKey("Discountsid")
                        .IsRequired()
                        .HasConstraintName("FK_PRODUCT DISCOUNTS_DISCOUNTS");

                    b.HasOne("RestaurantMenuDomain.Model.Product", "Products")
                        .WithMany()
                        .HasForeignKey("Productsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PRODUCT DISCOUNTS_PRODUCTS");

                    b.Navigation("Discounts");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("RestaurantMenuDomain.Model.Review", b =>
                {
                    b.HasOne("RestaurantMenuDomain.Model.Product", "Products")
                        .WithMany("Reviews")
                        .HasForeignKey("Productsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Products");
                });

            modelBuilder.Entity("RestaurantMenuDomain.Model.UserProduct", b =>
                {
                    b.HasOne("RestaurantMenuDomain.Model.Product", "Products")
                        .WithMany()
                        .HasForeignKey("Productsid")
                        .IsRequired()
                        .HasConstraintName("FK_USER PRODUCTS_PRODUCTS1");

                    b.HasOne("RestaurantMenuDomain.Model.User", "Users")
                        .WithMany()
                        .HasForeignKey("Usersid")
                        .IsRequired()
                        .HasConstraintName("FK_USER PRODUCTS_USERS");

                    b.Navigation("Products");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("RestaurantMenuDomain.Model.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("RestaurantMenuDomain.Model.Product", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
